const numberOpFunc = (_category) => ['==', '>', '<']

export const filter_options = [
    {
        columnField: "video_uid",
        type: "text",
        customOperatorFunc: (_category) => ['==', "!="]
    },
    {
        columnField: "benchmarks",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => benchmark_values,
    },
    {
        columnField: "modalities",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => modality_values,
    },
    {
        columnField: "narrations",
        type: "array[text]",
        customOperatorFunc: (_c) => ['contain', '!contain'],
    },
    {
        columnField: "scenarios",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => scenario_values,
    },
    {
        columnField: 'moments.activities',
        type: "array[text]",
        customOperatorFunc: (_c) => ['include', '!include'],
        customValuesFunc: (_c, _o) => moments_activity_values,
    },
    {
        columnField: 'nlq.query_templates',
        type: "array[text]",
        customOperatorFunc: (_c) => ['include', '!include'],
        customValuesFunc: (_c, _o) => nlq_query_template_values,
    },
    {
        columnField: "fho_lta.action_nouns",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => fho_lta_action_noun_values,
    },
    {
        columnField: "fho_lta.action_verbs",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => fho_lta_action_verb_values,
    },
    {
        columnField: "fho_scod.objects",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => fho_scod_object_values,
    },
    {
        columnField: "fho_sta.objects",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => fho_sta_object_values,
    },
    {
        columnField: "fho_sta.verbs",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => fho_sta_verb_values,
    },
    {
        columnField: "summaries",
        type: "array[text]",
        customOperatorFunc: (_c) => ['contain', '!contain'],
    },
    {
        columnField: "is_stereo",
        type: "text",
        customOperatorFunc: (_category) => ['==', "!="],
        customValuesFunc: (_c, _o) => ['true', 'false'],
    },
    {
        columnField: "split_av",
        type: "text",
        customOperatorFunc: (_c) => ['==', '!='],
        customValuesFunc: (_c, _o) => ['test', 'train', 'val'],
    },
    {
        columnField: "split_em",
        type: "text",
        customOperatorFunc: (_c) => ['==', '!='],
        customValuesFunc: (_c, _o) => ['test', 'train', 'val'],
    },
    {
        columnField: "split_fho",
        type: "text",
        customOperatorFunc: (_c) => ['==', '!='],
        customValuesFunc: (_c, _o) => ['test', 'train', 'val', 'multi'],
    },
    {
        columnField: "splits",
        type: "array[text]",
        customOperatorFunc: (_category) => ['include', '!include'],
        customValuesFunc: (_c, _o) => split_values,
    },
    {
        columnField: "device",
        type: "text",
        customOperatorFunc: (_category) => ['==', "!="],
        customValuesFunc: (_c, _o) => device_values,
    },
    {
        columnField: "physical_setting_name",
        type: "text",
        customOperatorFunc: (_category) => ['==', "!="],
        customValuesFunc: (_c, _o) => physical_setting_name_values,
    },
    {
        columnField: "dimensions",
        type: "text",
        customOperatorFunc: (_category) => ['==', "!="],
        customValuesFunc: (_c, _o) => dimension_values,
    },
    {
        columnField: "duration",
        type: "number",
        customOperatorFunc: numberOpFunc
    },
    {
        columnField: "num_frames",
        type: "number",
        customOperatorFunc: numberOpFunc
    },
    {
        columnField: "video_source",
        type: "text",
        customOperatorFunc: (_category) => ['==', "!="],
        customValuesFunc: (_c, _o) => video_source_values,
    },
];

export const moments_activity_values = [
    'apply_fertilizer_/_pesticide_by_hands_or_other_equipment',
    'apply_fertilizer_/_pesticide_with_sprayer',
    'arrange_/_organize_books_on_shelf',
    'arrange_/_organize_clothes_in_closet/dresser',
    'arrange_/_organize_furniture',
    'arrange_/_organize_items_in_fridge',
    'arrange_/_organize_other_items',
    'arrange_pillows_on_couch_/_chair',
    'assemble_a_salad',
    'assemble_a_sandwich',
    'beat_/_whisk_eggs_in_a_bowl',
    'blend_ingredients_using_an_electric_blender',
    'boil_rice_/_pasta_/_noodles',
    'boil_some_other_food_item',
    'break_eggs_into_a_bowl',
    'browse_through_accessories_on_rack_/_shelf',
    'browse_through_clothing_items_on_rack_/_shelf_/_hanger',
    'browse_through_groceries_or_food_items_on_rack_/_shelf',
    'browse_through_other_items_on_rack_/_shelf',
    'carve_wood_with_chisel,_carving_machine,_etc.',
    'charge_electronic_device',
    'chop_/_cut_wood_pieces_using_tool',
    'clean_/_arrange_shoes',
    'clean_/_empty_litterbox',
    'clean_/_empty_the_vacuum_cleaner',
    'clean_/_repair_small_equipment_(mower,_trimmer_etc.)',
    'clean_/_sweep_floor_with_broom',
    'clean_/_wipe_/_oil_metallic_item',
    'clean_/_wipe_a_table_or_kitchen_counter',
    'clean_/_wipe_kitchen_appliance',
    'clean_/_wipe_other_surface_or_object',
    'clean_hand_with_hand_sanitizer',
    'clean_something_with_air_blower',
    'clean_the_bathtub',
    'clean_the_sink',
    'clean_toilet_bowl',
    'clean_window',
    'climb_up_/_down_a_ladder',
    'collect_/_rake_dry_leaves_on_ground',
    'collect_firewood',
    'compare_two_clothing_items',
    'converse_/_interact_with_someone',
    'count_money_before_paying',
    'cross_the_road',
    'cut_/_chop_/_slice_a_vegetable,_fruit,_or_meat',
    'cut_/_trim_grass_with_a_lawnmower',
    'cut_/_trim_grass_with_other_tools',
    'cut_dough',
    'cut_metal_using_tool',
    'cut_open_a_package_(e.g._with_scissors)',
    'cut_other_item_using_tool',
    'cut_pipe_using_tool',
    'cut_straw/hay_with_sickle',
    'cut_thread_/_paper_/_cardboard_using_scissors_/_knife_/_cutter',
    'cut_tree_branch',
    'dance_to_music',
    'decorate_a_cake_/_cookie',
    'dig_or_till_the_soil_by_hand',
    'dig_or_till_the_soil_with_a_hoe_or_other_tool',
    'dismantle_a_bicycle',
    'dismantle_furniture_items',
    'dismantle_other_item',
    'do_some_exercise',
    'drill_into_wall_/_wood_/_floor_/_metal',
    'drink_beverage',
    'drive_a_vehicle',
    'eat_a_snack',
    'enter_a_supermarket_/_shop',
    'exit_a_supermarket_/_shop',
    'feed_pet_/_animal',
    'fill_a_bucket_with_water_from_a_tap_or_well',
    'fill_a_pot_/_bottle_/_container_with_water',
    'fix_/_remove_/_replace_a_tire_or_wheel',
    'fix_/_tile_the_floor',
    'fix_bicycle_/_bike_/_motorcycle_chain',
    'fix_bike_/_motorcycle_engine',
    'fix_bonnet_/_engine_of_car',
    'fix_furniture',
    'fix_metal_surface_using_electric_torch',
    'fix_other_item',
    'fix_pipe_/_plumbing',
    'fix_the_break_on_bike',
    'fix_wiring',
    'fold_clothes_/_sheets',
    'fry_dough',
    'fry_egg',
    'fry_meat',
    'fry_other_food_item',
    'gather_/_pack_bales_of_hay_or_straw',
    'gather_dirty_laundry',
    'grate_vegetables_or_other_ingredient',
    'grind_ingredients_/_spices',
    'hang_clothes_in_closet_/_on_hangers',
    'hang_clothes_to_dry',
    'harvest_vegetables_/_fruits_/_crops_from_plants_on_the_ground',
    'harvest_vegetables_/_fruits_/_crops_from_trees',
    'interact_or_play_with_pet_/_animal',
    'iron_clothes_or_sheets',
    'knead_/_shape_/_roll-out_dough',
    'level_ground_/_soil_(eg._using_rake,_shovel,_etc)',
    'load/unload_the_dishwasher',
    'load_/_unload_a_washing_machine_or_dryer',
    'look_at_clothes_in_the_mirror',
    'make_coffee_or_tea_/_use_a_coffee_machine',
    'make_pancakes',
    'make_the_bed_/_arrange_pillows,_sheets_etc._on_bed',
    'make_toast_/_use_a_toaster',
    'mark_item_with_pencil_/_pen_/_marker',
    'measure_bricks_using_tape_/_ruler',
    'measure_ingredient_in_a_measuring_cup_or_spoon',
    'measure_other_item_using_tape_/_ruler',
    'measure_site_using_laser_level',
    'measure_tile_using_tape_/_ruler',
    'measure_wall_/_ceiling_/_flooring_using_tape,_ruler',
    'measure_wooden_item_using_tape_/_ruler',
    'mop_the_floor',
    'move_/_shift_/_arrange_small_tools',
    'move_/_shift_around_construction_material',
    'open_a_can_with_a_can_opener',
    'operate_a_dough_mixing_machine',
    'operate_a_forklift',
    'operate_a_water_hose',
    'pack_bag/sack_with_crops_or_grass',
    'pack_food_items_/_groceries_into_bags_/_boxes',
    'pack_other_items_into_bags_/_boxes',
    'pack_soil_into_the_ground_or_a_pot_/_container',
    'paint_using_paint_brush_/_roller',
    'pay_at_billing_counter',
    'peel_a_fruit_or_vegetable',
    'place_items_in_shopping_cart',
    'plant_seeds_/_plants_/_flowers_into_ground',
    'plaster_wall_/_surface',
    'play_a_video_game',
    'play_board_game_or_card_game',
    'play_the_piano',
    'prepare_or_apply_cement_/_concrete_/_mortar',
    'pump_/_fill_/_pressurize_a_tire',
    'put_away_(or_take_out)_dishes_/_utensils_in_storage',
    'put_away_(or_take_out)_food_items_in_the_fridge',
    'put_away_(or_take_out)_ingredients_in_storage',
    'put_food_into_the_oven_to_bake',
    'put_fuel_in_stove_/_fireplace',
    'put_on_/_take_off_an_apron',
    'put_on_safety_equipment_(e.g._gloves,_helmet,_safety_goggles)',
    'put_up_decorations_in_a_room',
    're-fuel_vehicle_/_equipment',
    'read_a_book_/_magazine_/_shopping_list_etc.',
    'refill_water/chemical_into_sprayer',
    'remove_food_from_the_oven',
    'remove_husk_from_crops',
    'remove_paint_from_wall_/_ceiling_/_furniture',
    'remove_weeds_from_ground',
    'request_and_eat_a_food_sample',
    'rinse_/_drain_noodles_in_sieve_/_colander',
    'rinse_/_drain_other_food_item_in_sieve_/_colander',
    'serve_food_onto_a_plate',
    'set_the_table',
    'sew_/_knit_/_crochet_/_mend_some_fabric',
    'sharpen_knife_/_blade_/_cutter',
    'sift_ingredients',
    'smoke_cigar_/_cigarette_/_vape',
    'smooth_floor_surface_using_trowel',
    'smooth_other_surface_(eg._using_sandpaper)',
    'smooth_wood_using_sandpaper_/_sander_/_tool',
    'sort_trash_/_recycling_material',
    'spread_cheese_/_jelly_/_butter_/_etc._on_bread',
    'squeeze_juice_from_a_fruit_(lemon,_lime,_etc.)',
    'stand_in_the_queue_/_line_at_a_shop_/_supermarket',
    'stick_items_together_using_glue_/_staple_/_tape_/_adhesive',
    'stir_/_mix_food_while_cooking',
    'stir_/_mix_ingredients_in_a_bowl_or_pan_(before_cooking)',
    'store_leftover_food_in_box_/_container',
    'take_off_clothing_item',
    'take_out_the_trash_/_empty_the_trash_bin',
    'take_photo_/_record_video_with_a_camera',
    'taste_food_while_cooking',
    'throw_away_trash_/_put_trash_in_trash_can',
    'tie_up_branches_/_plants_with_string',
    'trim_hedges_or_branches',
    'try-out_/_wear_accessories_(e.g._tie,_belt,_scarf)',
    'try-out_/_wear_clothing_items_(e.g._shirt,_jeans,_sweater)',
    'turn-on_/_light_the_stove_burner',
    'use_a_laptop_/_computer',
    'use_a_pressure_cooker_/_instant_pot',
    'use_a_vacuum_cleaner_to_clean',
    'use_hammer_/_nail-gun_to_fix_nail',
    'use_leveler_to_balance_surface',
    'use_other_kitchen_appliance',
    'use_phone',
    'use_the_microwave_/_warm_something_in_the_microwave',
    'walk_down_stairs_/_walk_up_stairs',
    'walk_the_dog_/_pet',
    'wash_clothes_by_hand',
    'wash_dishes_/_utensils_/_bakeware_etc.',
    'wash_hands',
    'wash_vegetable_/_fruit_/_food_item',
    'watch_television',
    'water_soil_/_plants_/_crops',
    'weigh_food_/_ingredient_using_a_weighing_scale',
    'weld_metallic_item',
    'withdraw_money_from_atm_/_operate_atm',
    'wrap_food_in_paper_/_foil_/_plastic',
    'write_notes_in_a_paper_/_book'
];

export const nlq_query_template_values = [
    'Objects: How many X’s? (quantity question)',
    'Objects: In what location did I see object X ?',
    'Objects: State of an object',
    'Objects: What X did I Y?',
    'Objects: What X is Y?',
    'Objects: What did I put in X?',
    'Objects: Where is my object X?',
    'Objects: Where is object X before / after event Y?',
    'Objects: Where is object X?',
    'People: When did I talk to or interact with person with role X?',
    'People: Who did I interact with when I did activity X?',
    'People: Who did I talk to in location X?',
    'Place: Where did I put X?'
];

export const fho_sta_verb_values = [
    'adjust_(regulate,_increase/reduce,_change)',
    'apply_(spread,_smear)',
    'arrange_(straighten,_sort,_distribute,_align)',
    'attach_(plug-in,_join,_fasten,_connect,_attach)',
    'clean_(sweep,_scrub,_mop,_dust)',
    'climb',
    'close',
    'consume_(taste,_sip,_eat,_drink)',
    'cut_(trim,_slice,_chop)',
    'detach_(unplug,_unhook,_disconnect)',
    'dig',
    'dip',
    'divide_(split,_separate)',
    'drill',
    'drive_(ride,_drive)',
    'file_(with_tool)',
    'fill',
    'fold',
    'give',
    'grate',
    'hang',
    'hit_(knock,_hit,_hammer)',
    'hold_(support,_grip,_grasp)',
    'insert',
    'inspect_(check,_look,_examine,_view)',
    'iron',
    'kick',
    'knead',
    'loosen',
    'mark',
    'measure_(weigh,_measure)',
    'mold',
    'move_(transfer,_pass,_exchange)',
    'open',
    'operate_(use,_dial,_click-button)',
    'pack',
    'paint_draw',
    'peel',
    'plant',
    'play',
    'pour',
    'press_push',
    'pump',
    'put_(place,_leave,_drop)',
    'repair',
    'roll',
    'sand',
    'scoop',
    'scrape',
    'screw',
    'scroll',
    'search_inspect',
    'serve',
    'sew_(weave,_stitch,_sew)',
    'shake',
    'shuffle',
    'smooth',
    'spray',
    'squeeze',
    'stick_(tape,_stick,_glue)',
    'take_(pick,_grab,_get)',
    'throw_(toss,_dump,_dispose)',
    'tie',
    'tighten',
    'touch',
    'turn_(spin,_rotate,_flip,_turn_over)',
    'turn_off_(turn_off,_switch_off)',
    'turn_on_(switch_on,_start,_light)',
    'unscrew',
    'water',
    'weld',
    'write'
];

export const fho_sta_object_values = [
    'artwork_(art,_draw,_drawing,_painting,_sketch)',
    'bag_(bag,_grocery,_nylon,_polythene,_pouch,_sachet,_sack,_suitcase)',
    'ball_(ball,_baseball,_basketball)',
    'bicycle_(bicycle,_bike)',
    'book_(book,_booklet,_magazine,_manual,_notebook,_novel,_page,_textbook)',
    'bottle_(bottle,_flask)',
    'bowl',
    'brick',
    'broom_(broom,_broomstick)',
    'brush',
    'bucket',
    'cabinet_(cabinet,_compartment,_cupboard)',
    'caliper',
    'car_(car,_vehicle)',
    'cement_(cement,_concrete,_mortar)',
    'computer_(computer,_ipad,_laptop,_motherboard,_screen)',
    'container_(box,_can,_carton,_case,_casing,_container,_crate,_holder,_jar,_jerrycan,_keg,_pack,_package,_packaging,_packet,_storage,_tank,_tin)',
    'cooker',
    'cup_(cup,_mug,_tumbler)',
    'cutter_(tool)',
    'door',
    'dough',
    'drawer',
    'drill_(drill,_driller)',
    'dumbbell',
    'engine_(assembly,_carburetor,_engine,_motor)',
    'faucet_(faucet,_tap)',
    'floor_(floor,_ground)',
    'flower',
    'food',
    'fridge_(fridge,_refrigerator)',
    'glass',
    'glue_(adhesive,_glue,_gum,_sealant)',
    'hammer_(hammer,_mallet)',
    'indument',
    'jug',
    'knife_(knife,_machete)',
    'lid_(cap,_cover,_lid)',
    'mask',
    'mat_(mat,_rug)',
    'metal_(lead,_metal,_steel)',
    'mold_(mold,_molder,_mould)',
    'mop',
    'mower_(lawnmower,_mower)',
    'napkin_(handkerchief,_napkin,_serviette,_tissue,_wipe)',
    'needle_(hook,_needle)',
    'nut_(tool)',
    'paint',
    'pan_(frypan,_pan,_saucepan)',
    'paper_(chart,_craft,_newspaper,_note,_paper,_papercraft,_poster,_receipt)',
    'pedal',
    'pen_(marker,_pen)',
    'phone_(cellphone,_phone,_smartphone)',
    'plant',
    'plate_(dish,_plate,_platter,_saucer)',
    'playing_cards',
    'pot',
    'pump',
    'rod_(dipstick,_rod,_rod_metal,_shaft)',
    'rope',
    'rubber_band',
    'saw_(chainsaw,_saw,_hacksaw)',
    'scissors',
    'screw_(bolt,_nail,_screw)',
    'screwdriver',
    'shelf',
    'shoe_(boot,_sandal,_shoe,_slipper)',
    'sickle',
    'sieve_(sieve,_strainer)',
    'spatula',
    'sponge_(scrubber,_sponge)',
    'spoon',
    'stone_(rock,_stone)',
    'string_(bobbin,_knot,_lace,_ribbon,_spool,_strand,_string,_thread,_twine,_wool,_yarn)',
    'table_(stand,_table)',
    'tablet',
    'tape_measure_(measure,_measurement)',
    'tile',
    'towel',
    'trash',
    'tray',
    'vegetable_fruit',
    'wall',
    'wheel',
    'wire_(adapter,_cable,_charger,_connector,_cord,_wire)',
    'wood_(fiber,_firewood,_floorboard,_log,_lumber,_plank,_plywood,_timber,_wood,_woodcraft,_woodwork)',
    'wrench'
];

export const fho_scod_object_values = [
    'apron',
    'artwork_(art,_draw,_drawing,_painting,_sketch)',
    'asparagus',
    'avocado',
    'awl',
    'axe',
    'baby',
    'bacon',
    'bag_(bag,_grocery,_nylon,_polythene,_pouch,_sachet,_sack,_suitcase)',
    'baking_soda',
    'ball_(ball,_baseball,_basketball)',
    'ball_bearing',
    'banana_(banana,_plantain)',
    'bar',
    'baseboard',
    'basket',
    'bat_(sports)',
    'bat_(tool)',
    'batter_(batter,_mixture)',
    'battery',
    'bead',
    'beaker',
    'bean',
    'bed',
    'belt',
    'bench',
    'berry',
    'beverage_(drink,_juice,_beer,_beverage,_champagne)',
    'bicycle_(bicycle,_bike)',
    'blanket_(bedsheet,_blanket,_duvet)',
    'blender',
    'block_(material)',
    'blower',
    'bolt_extractor',
    'book_(book,_booklet,_magazine,_manual,_notebook,_novel,_page,_textbook)',
    'bookcase',
    'bottle_(bottle,_flask)',
    'bowl',
    'bracelet_(bangle,_bracelet)',
    'brake_(brake,_break)',
    'brake_pad',
    'branch',
    'bread_(bread,_bun,_chapati,_flatbread,_loaf,_roti,_tortilla)',
    'brick',
    'broccoli',
    'broom_(broom,_broomstick)',
    'brush',
    'bucket',
    'buckle',
    'butter',
    'button',
    'cabbage',
    'cabinet_(cabinet,_compartment,_cupboard)',
    'calculator',
    'caliper',
    'camera',
    'can_opener',
    'canvas',
    'car_(car,_vehicle)',
    'card',
    'cardboard_(cardboard,_paperboard)',
    'carpet',
    'carrot',
    'cart_(cart,_trolley)',
    'ceiling',
    'celery',
    'cello',
    'cement_(cement,_concrete,_mortar)',
    'cereal',
    'chaff',
    'chain',
    'chair',
    'chalk',
    'cheese',
    'chicken',
    'chip_(food)',
    "chip_(wood'_metal),",
    'chip_(wood,_metal)',
    'chisel',
    'chocolate',
    'chopping_board',
    'chopstick',
    'cigarette_(cigarette,_vape)',
    'circuit',
    'clamp',
    'clay',
    'clip',
    'clock',
    'cloth_(cloth,_fabric,_garment,_kanga,_rag)',
    'coffee',
    'coffee_machine',
    'colander',
    'comb',
    'computer_(computer,_ipad,_laptop,_motherboard,_screen)',
    'container_(box,_can,_carton,_case,_casing,_container,_crate,_holder,_jar,_jerrycan,_keg,_pack,_package,_packaging,_packet,_storage,_tank,_tin)',
    'cooker',
    'corn',
    'corner',
    'countertop_(counter,_countertop)',
    'cracker_(biscuit,_cracker)',
    'cream',
    'crochet',
    'crowbar',
    'cucumber',
    'cup_(cup,_mug,_tumbler)',
    'curtain',
    'cutter_(tool)',
    'decoration_(decoration,_ornament)',
    'derailleur',
    'detergent',
    'dice_(dice,_die)',
    'dishwasher',
    'dog',
    'door',
    'dough',
    'dough_mixer',
    'doughnut',
    'drawer',
    'dress',
    'drill_(drill,_driller)',
    'drill_bit',
    'drum',
    'dumbbell',
    'dust_(dust,_sawdust)',
    'dustpan',
    'egg',
    'engine_(assembly,_carburetor,_engine,_motor)',
    'envelope_(envelop,_envelope)',
    'eraser_(eraser,_rubber)',
    'facemask',
    'fan',
    'faucet_(faucet,_tap)',
    'fence',
    'file_(tool)',
    'filter',
    'fish',
    'fishing_rod',
    'floor_(floor,_ground)',
    'flour',
    'flower',
    'foam',
    'foil',
    'food',
    'foot_(foot,_toe)',
    'fork',
    'fridge_(fridge,_refrigerator)',
    'fries',
    'fuel',
    'funnel',
    'game_controller',
    'garbage_can_(bin,_dustbin)',
    'garlic',
    'gasket',
    'gate',
    'gauge',
    'gauze',
    'gear',
    'generator',
    'ginger',
    'glass',
    'glasses_(goggle,_shade,_spectacle,_sunglass)',
    'glove',
    'glue_(adhesive,_glue,_gum,_sealant)',
    'glue_gun',
    'golf_club',
    'gourd',
    'grain',
    'grapefruit',
    'grass',
    'grater',
    'grill',
    'grinder',
    'guava',
    'guitar',
    'hair',
    'hammer_(hammer,_mallet)',
    'hand_(finger,_hand,_palm,_thumb)',
    'handle',
    'hanger',
    'hat',
    'hay',
    'haystack',
    'head',
    'headphones_(earphone,_headphone)',
    'heater',
    'helmet',
    'hinge',
    'hole',
    'hose',
    'ice',
    'ice_cream',
    'ink',
    'iron',
    'jack_(tool)_(jack,_lift)',
    'jacket_(coat,_jacket)',
    'jug',
    'ketchup',
    'kettle',
    'key',
    'keyboard',
    'knife_(knife,_machete)',
    'label_(label,_tag)',
    'ladder',
    'leaf_(leaf,_leave)',
    'leash',
    'leg_(knee,_leg,_thigh)',
    'lever',
    'lid_(cap,_cover,_lid)',
    'light_(bulb,_flashlight,_lamp,_light)',
    'lighter',
    'lime',
    'lock',
    'lubricant_(grease,_lubricant)',
    'magnet_(magnet,_sphere)',
    'manure_(dung,_manure)',
    'mask',
    'mat_(mat,_rug)',
    'matchstick',
    'meat_(beef,_ham,_meat)',
    'metal_(lead,_metal,_steel)',
    'microscope',
    'microwave',
    'milk',
    'mirror',
    'mixer',
    'mold_(mold,_molder,_mould)',
    'money_(cash,_coin,_money)',
    'mop',
    'motorcycle_(motorbike,_motorcycle)',
    'mouse_(computer)',
    'mouth',
    'mower_(lawnmower,_mower)',
    'multimeter',
    'mushroom',
    'nail_cutter',
    'nail_gun',
    'nail_polish',
    'napkin_(handkerchief,_napkin,_serviette,_tissue,_wipe)',
    'needle_(hook,_needle)',
    'net',
    'nozzle',
    'nut_(food)',
    'nut_(tool)',
    'oil_(fat,_oil)',
    'okra',
    'onion',
    'oven',
    'paddle',
    'paint',
    'paint_roller',
    'paintbrush',
    'palette',
    'pan_(frypan,_pan,_saucepan)',
    'pancake',
    'panel',
    'pants_(jean,_pant,_short,_trouser)',
    'paper_(chart,_craft,_newspaper,_note,_paper,_papercraft,_poster,_receipt)',
    'pasta_(noodle,_pasta,_spaghetti)',
    'paste',
    'pastry',
    'pea',
    'peanut',
    'pear',
    'pedal',
    'peel',
    'peeler',
    'peg',
    'pen_(marker,_pen)',
    'pencil',
    'pepper_(vegetable)_(capsicum,_pepper)',
    'phone_(cellphone,_phone,_smartphone)',
    'photo',
    'piano',
    'picture_(picture,_portrait)',
    'pillow',
    'pilot_jet',
    'pin',
    'pipe',
    'pizza',
    'planer_(plane,_planer)',
    'plant_(bud,_frond,_plant,_reed,_seedling,_shrub,_stem,_vine,_weed)',
    'plate_(dish,_plate,_platter,_saucer)',
    'playing_cards',
    'plier',
    'plug',
    'pole',
    'popcorn',
    'pot',
    'pot_(planter)',
    'potato',
    'pump',
    'pumpkin',
    'purse',
    'puzzle_or_game_piece_(chess,_domino,_jenga,_jigsaw,_pawn,_puzzle)',
    'rack',
    'radio',
    'rail_(rail,_railing)',
    'rake',
    'razor_blade',
    'remote_control_(control,_remote)',
    'rice',
    'ring',
    'rod_(dipstick,_rod,_rod_metal,_shaft)',
    'rolling_pin',
    'root',
    'rope',
    'router',
    'rubber_band',
    'ruler_(rule,_ruler)',
    'sand',
    'sander',
    'sandpaper',
    'sauce',
    'sausage',
    'saw_(chainsaw,_saw,_hacksaw)',
    'scarf_(scarf,_shawl)',
    'scissors',
    'scoop_(scoop,_scooper)',
    'scraper_(scraper,_scrapper)',
    'screw_(bolt,_nail,_screw)',
    'screwdriver',
    'sculpture',
    'seasoning_(salt,_seasoning,_shaker,_spice,_sugar)',
    'seed',
    'set_square_(tool)',
    'sewing_machine',
    'shears',
    'sheet',
    'shelf',
    'shirt_(cardigan,_shirt,_sweater,_sweatshirt,_top)',
    'shoe_(boot,_sandal,_shoe,_slipper)',
    'shovel_(hoe,_shovel,_spade)',
    'sickle',
    'sieve_(sieve,_strainer)',
    'sink_(basin,_sink)',
    'sketch_pad',
    'skirt',
    'slab',
    'snorkel',
    'soap',
    'sock',
    'socket',
    'soil_(dirt,_mud,_soil)',
    'solder_iron',
    'soup',
    'spatula',
    'speaker',
    'sphygmomanometer',
    'spice',
    'spinach',
    'spirit_level',
    'sponge_(scrubber,_sponge)',
    'spoon_(spoon,_spoonful)',
    'spray_(spray,_sprayer)',
    'spring',
    'squeezer',
    'stairs_(stair,_staircase)',
    'stamp',
    'stapler',
    'steamer',
    'steering_wheel',
    'stick_(stick,_twig)',
    'sticker',
    'stock_(food)',
    'stone_(rock,_stone)',
    'stool',
    'stove_(burner,_gas,_stove)',
    'strap',
    'straw',
    'string_(bobbin,_knot,_lace,_ribbon,_spool,_strand,_string,_thread,_twine,_wool,_yarn)',
    'switch_(knob,_switch)',
    'syringe',
    'table_(stand,_table)',
    'tablet',
    'tape_(cellotape,_sellotape,_tape)',
    'tape_measure_(measure,_measurement)',
    'tea',
    'teapot',
    'television_(television,_tv)',
    'test_tube',
    'tie',
    'tile',
    'timer',
    'toaster',
    'tomato',
    'tongs',
    'toolbox',
    'toothbrush',
    'toothpick',
    'torch_(torch,_torchlight)',
    'towel',
    'toy_(doll,_toy)',
    'tractor',
    'trash_(debris,_garbage,_litter,_trash,_waste)',
    'tray',
    'treadmill',
    'tree',
    'trimmer_(pruner,_trimmer)',
    'trowel',
    'truck',
    'tweezer',
    'umbrella',
    'undergarment_(boxer,_bra)',
    'vacuum',
    'vacuum_cleaner',
    'valve',
    'vase',
    'wall',
    'wallet',
    'wallpaper',
    'washing_machine',
    'watch',
    'water',
    'watermelon',
    'weighing_scale',
    'welding_torch',
    'wheat_(maize,_wheat)',
    'wheel_(tyre,_wheel)',
    'whisk',
    'window',
    'windshield',
    'wiper_(car)',
    'wire_(adapter,_cable,_charger,_connector,_cord,_wire)',
    'wood_(fiber,_firewood,_floorboard,_log,_lumber,_plank,_plywood,_timber,_wood,_woodcraft,_woodwork)',
    'worm',
    'wrapper_(covering,_film,_seal,_wrap,_wrapper,_wrapping)',
    'wrench_(spanner,_wrench)',
    'yam',
    'yeast',
    'yoghurt',
    'zipper_(zip,_zipper)',
    'zucchini'
];

export const fho_lta_action_verb_values = [
    'adjust_(regulate,_increase/reduce,_change)',
    'apply_(spread,_smear)',
    'arrange_(straighten,_sort,_distribute,_align)',
    'attach_(plug-in,_join,_fasten,_connect,_attach)',
    'blow',
    'break',
    'carry',
    'catch',
    'clap',
    'clean_(sweep,_scrub,_mop,_dust)',
    'climb',
    'close',
    'consume_(taste,_sip,_eat,_drink)',
    'count',
    'cover',
    'crochet',
    'cut_(trim,_slice,_chop)',
    'detach_(unplug,_unhook,_disconnect)',
    'dig',
    'dip',
    'divide_(split,_separate)',
    'draw',
    'drill',
    'drive_(ride,_drive)',
    'enter',
    'feed',
    'file_(with_tool)',
    'fill',
    'fold',
    'give',
    'grate',
    'grind',
    'hang',
    'hit_(knock,_hit,_hammer)',
    'hold_(support,_grip,_grasp)',
    'insert',
    'inspect_(check,_look,_examine,_view)',
    'iron',
    'kick',
    'knead',
    'knit',
    'lift',
    'lock',
    'loosen',
    'mark',
    'measure_(weigh,_measure)',
    'mix',
    'mold',
    'move_(transfer,_pass,_exchange)',
    'open',
    'operate_(use,_dial,_click-button)',
    'pack',
    'paint',
    'park',
    'peel',
    'pet',
    'plant',
    'play',
    'point',
    'pour',
    'press',
    'pull',
    'pump',
    'push',
    'put_(place,_leave,_drop)',
    'read',
    'remove',
    'repair',
    'roll',
    'sand',
    'scoop',
    'scrape',
    'screw',
    'scroll',
    'search',
    'serve',
    'sew_(weave,_stitch,_sew)',
    'shake',
    'sharpen',
    'shuffle',
    'sieve',
    'sit',
    'smooth',
    'spray',
    'sprinkle',
    'squeeze',
    'stand',
    'step',
    'stick_(tape,_stick,_glue)',
    'stretch',
    'swing',
    'take_(pick,_grab,_get)',
    'throw_(toss,_dump,_dispose)',
    'tie',
    'tighten',
    'tilt',
    'touch',
    'turn_(spin,_rotate,_flip,_turn_over)',
    'turn_off_(turn_off,_switch_off)',
    'turn_on_(switch_on,_start,_light)',
    'uncover',
    'unfold',
    'unroll',
    'unscrew',
    'untie',
    'walk',
    'wash',
    'water',
    'wear',
    'weld',
    'wipe',
    'write',
    'zip'
];

export const fho_lta_action_noun_values = [
    'apple',
    'apron',
    'arm',
    'artwork_(art,_draw,_drawing,_painting,_sketch)',
    'asparagus',
    'avocado',
    'awl',
    'axe',
    'baby',
    'bacon',
    'bag_(bag,_grocery,_nylon,_polythene,_pouch,_sachet,_sack,_suitcase)',
    'baking_soda',
    'ball_(ball,_baseball,_basketball)',
    'ball_bearing',
    'balloon',
    'banana_(banana,_plantain)',
    'bar',
    'baseboard',
    'basket',
    'bat_(sports)',
    'bat_(tool)',
    'bathtub',
    'batter_(batter,_mixture)',
    'battery',
    'bead',
    'beaker',
    'bean',
    'bed',
    'belt',
    'bench',
    'berry',
    'beverage_(drink,_juice,_beer,_beverage,_champagne)',
    'bicycle_(bicycle,_bike)',
    'blanket_(bedsheet,_blanket,_duvet)',
    'blender',
    'block_(material)',
    'blower',
    'bolt_extractor',
    'book_(book,_booklet,_magazine,_manual,_notebook,_novel,_page,_textbook)',
    'bookcase',
    'bottle_(bottle,_flask)',
    'bowl',
    'bracelet_(bangle,_bracelet)',
    'brake_(brake,_break)',
    'brake_pad',
    'branch',
    'bread_(bread,_bun,_chapati,_flatbread,_loaf,_roti,_tortilla)',
    'brick',
    'broccoli',
    'broom_(broom,_broomstick)',
    'brush',
    'bucket',
    'buckle',
    'butter',
    'button',
    'cabbage',
    'cabinet_(cabinet,_compartment,_cupboard)',
    'calculator',
    'caliper',
    'camera',
    'can_opener',
    'canvas',
    'car_(car,_vehicle)',
    'card',
    'cardboard_(cardboard,_paperboard)',
    'carpet',
    'carrot',
    'cart_(cart,_trolley)',
    'cat',
    'ceiling',
    'celery',
    'cello',
    'cement_(cement,_concrete,_mortar)',
    'cereal',
    'chaff',
    'chain',
    'chair',
    'cheese',
    'chicken',
    'chip_(food)',
    "chip_(wood'_metal),",
    'chip_(wood,_metal)',
    'chisel',
    'chocolate',
    'chopping_board',
    'chopstick',
    'cigarette_(cigarette,_vape)',
    'circuit',
    'clamp',
    'clay',
    'clip',
    'clock',
    'cloth_(cloth,_fabric,_garment,_kanga,_rag)',
    'coffee',
    'coffee_machine',
    'colander',
    'comb',
    'computer_(computer,_ipad,_laptop,_motherboard,_screen)',
    'container_(box,_can,_carton,_case,_casing,_container,_crate,_holder,_jar,_jerrycan,_keg,_pack,_package,_packaging,_packet,_storage,_tank,_tin)',
    'cooker',
    'cookie',
    'cork',
    'corn',
    'corner',
    'countertop_(counter,_countertop)',
    'cracker_(biscuit,_cracker)',
    'crayon',
    'cream',
    'crochet',
    'crowbar',
    'cucumber',
    'cup_(cup,_mug,_tumbler)',
    'curtain',
    'cutter_(tool)',
    'decoration_(decoration,_ornament)',
    'derailleur',
    'detergent',
    'dice_(dice,_die)',
    'dishwasher',
    'dog',
    'door',
    'dough',
    'dough_mixer',
    'doughnut',
    'drawer',
    'dress',
    'drill_(drill,_driller)',
    'drill_bit',
    'drum',
    'dumbbell',
    'dust_(dust,_sawdust)',
    'dustpan',
    'egg',
    'engine_(assembly,_carburetor,_engine,_motor)',
    'envelope_(envelop,_envelope)',
    'eraser_(eraser,_rubber)',
    'facemask',
    'fan',
    'faucet_(faucet,_tap)',
    'fence',
    'file_(tool)',
    'filler',
    'filter',
    'fish',
    'fishing_rod',
    'floor_(floor,_ground)',
    'flour',
    'flower',
    'foam',
    'foil',
    'food',
    'foot_(foot,_toe)',
    'fork',
    'fridge_(fridge,_refrigerator)',
    'fries',
    'fuel',
    'funnel',
    'game_controller',
    'garbage_can_(bin,_dustbin)',
    'garlic',
    'gasket',
    'gate',
    'gauge',
    'gauze',
    'gear',
    'generator',
    'ginger',
    'glass',
    'glasses_(goggle,_shade,_spectacle,_sunglass)',
    'glove',
    'glue_(adhesive,_glue,_gum,_sealant)',
    'glue_gun',
    'golf_club',
    'gourd',
    'grain',
    'grapefruit',
    'grass',
    'grater',
    'grill',
    'grinder',
    'guava',
    'guitar',
    'hair',
    'hammer_(hammer,_mallet)',
    'hand_(finger,_hand,_palm,_thumb)',
    'handle',
    'hanger',
    'hat',
    'hay',
    'haystack',
    'head',
    'headphones_(earphone,_headphone)',
    'heater',
    'helmet',
    'hinge',
    'hole',
    'horse',
    'hose',
    'ice',
    'ice_cream',
    'ink',
    'iron',
    'jack_(tool)_(jack,_lift)',
    'jacket_(coat,_jacket)',
    'jug',
    'kale',
    'ketchup',
    'kettle',
    'key',
    'keyboard',
    'knife_(knife,_machete)',
    'label_(label,_tag)',
    'ladder',
    'leaf_(leaf,_leave)',
    'leash',
    'leg_(knee,_leg,_thigh)',
    'lever',
    'lid_(cap,_cover,_lid)',
    'light_(bulb,_flashlight,_lamp,_light)',
    'lighter',
    'lime',
    'lock',
    'lubricant_(grease,_lubricant)',
    'magnet_(magnet,_sphere)',
    'mango',
    'manure_(dung,_manure)',
    'mask',
    'mat_(mat,_rug)',
    'matchstick',
    'meat_(beef,_ham,_meat)',
    'medicine',
    'metal_(lead,_metal,_steel)',
    'microscope',
    'microwave',
    'milk',
    'mirror',
    'mixer',
    'mold_(mold,_molder,_mould)',
    'money_(cash,_coin,_money)',
    'mop',
    'motorcycle_(motorbike,_motorcycle)',
    'mouse_(computer)',
    'mouth',
    'mower_(lawnmower,_mower)',
    'multimeter',
    'mushroom',
    'nail_cutter',
    'nail_gun',
    'nail_polish',
    'napkin_(handkerchief,_napkin,_serviette,_tissue,_wipe)',
    'needle_(hook,_needle)',
    'net',
    'nozzle',
    'nut_(food)',
    'nut_(tool)',
    'oil_(fat,_oil)',
    'okra',
    'onion',
    'oven',
    'paddle',
    'paint',
    'paint_roller',
    'paintbrush',
    'palette',
    'pan_(frypan,_pan,_saucepan)',
    'pancake',
    'panel',
    'pants_(jean,_pant,_short,_trouser)',
    'papaya',
    'paper_(chart,_craft,_newspaper,_note,_paper,_papercraft,_poster,_receipt)',
    'pasta_(noodle,_pasta,_spaghetti)',
    'paste',
    'pastry',
    'pea',
    'peanut',
    'pear',
    'pedal',
    'peel',
    'peeler',
    'peg',
    'pen_(marker,_pen)',
    'pencil',
    'pepper_(vegetable)_(capsicum,_pepper)',
    'phone_(cellphone,_phone,_smartphone)',
    'photo',
    'piano',
    'picture_(picture,_portrait)',
    'pie',
    'pillow',
    'pilot_jet',
    'pin',
    'pipe',
    'pizza',
    'planer_(plane,_planer)',
    'plant_(bud,_frond,_plant,_reed,_seedling,_shrub,_stem,_vine,_weed)',
    'plate_(dish,_plate,_platter,_saucer)',
    'playing_cards',
    'plier',
    'plug',
    'pole',
    'popcorn',
    'pot',
    'pot_(planter)',
    'potato',
    'pump',
    'pumpkin',
    'purse',
    'puzzle_or_game_piece_(chess,_domino,_jenga,_jigsaw,_pawn,_puzzle)',
    'rack',
    'radio',
    'rail_(rail,_railing)',
    'rake',
    'razor_blade',
    'remote_control_(control,_remote)',
    'rice',
    'ring',
    'rod_(dipstick,_rod,_rod_metal,_shaft)',
    'rolling_pin',
    'root',
    'rope',
    'router',
    'rubber_band',
    'ruler_(rule,_ruler)',
    'sand',
    'sander',
    'sandpaper',
    'sauce',
    'sausage',
    'saw_(chainsaw,_saw,_hacksaw)',
    'scarf_(scarf,_shawl)',
    'scissors',
    'scoop_(scoop,_scooper)',
    'scraper_(scraper,_scrapper)',
    'screw_(bolt,_nail,_screw)',
    'screwdriver',
    'sculpture',
    'seasoning_(salt,_seasoning,_shaker,_spice,_sugar)',
    'seed',
    'set_square_(tool)',
    'sewing_machine',
    'sharpener',
    'shears',
    'sheet',
    'shelf',
    'shirt_(cardigan,_shirt,_sweater,_sweatshirt,_top)',
    'shoe_(boot,_sandal,_shoe,_slipper)',
    'shovel_(hoe,_shovel,_spade)',
    'shower_head',
    'sickle',
    'sieve_(sieve,_strainer)',
    'sink_(basin,_sink)',
    'sketch_pad',
    'skirt',
    'slab',
    'snorkel',
    'soap',
    'sock',
    'socket',
    'soil_(dirt,_mud,_soil)',
    'solder_iron',
    'soup',
    'spatula',
    'speaker',
    'sphygmomanometer',
    'spice',
    'spinach',
    'spirit_level',
    'sponge_(scrubber,_sponge)',
    'spoon_(spoon,_spoonful)',
    'spray_(spray,_sprayer)',
    'spring',
    'squeezer',
    'stairs_(stair,_staircase)',
    'stamp',
    'stapler',
    'steamer',
    'steering_wheel',
    'stick_(stick,_twig)',
    'sticker',
    'stock_(food)',
    'stone_(rock,_stone)',
    'stool',
    'stove_(burner,_gas,_stove)',
    'strap',
    'straw',
    'string_(bobbin,_knot,_lace,_ribbon,_spool,_strand,_string,_thread,_twine,_wool,_yarn)',
    'switch_(knob,_switch)',
    'syringe',
    'table_(stand,_table)',
    'tablet',
    'tape_(cellotape,_sellotape,_tape)',
    'tape_measure_(measure,_measurement)',
    'tea',
    'teapot',
    'test_tube',
    'tie',
    'tile',
    'timer',
    'toaster',
    'tomato',
    'tongs',
    'toolbox',
    'toothbrush',
    'toothpick',
    'torch_(torch,_torchlight)',
    'towel',
    'toy_(doll,_toy)',
    'tractor',
    'trash_(debris,_garbage,_litter,_trash,_waste)',
    'tray',
    'treadmill',
    'tree',
    'trimmer_(pruner,_trimmer)',
    'trowel',
    'truck',
    'tweezer',
    'umbrella',
    'undergarment_(boxer,_bra)',
    'vacuum',
    'vacuum_cleaner',
    'valve',
    'vase',
    'video_game',
    'violin',
    'wall',
    'wallet',
    'wallpaper',
    'washing_machine',
    'watch',
    'water',
    'watermelon',
    'weighing_scale',
    'welding_torch',
    'wheat_(maize,_wheat)',
    'wheel_(tyre,_wheel)',
    'whisk',
    'window',
    'windshield',
    'wiper_(car)',
    'wire_(adapter,_cable,_charger,_connector,_cord,_wire)',
    'wood_(fiber,_firewood,_floorboard,_log,_lumber,_plank,_plywood,_timber,_wood,_woodcraft,_woodwork)',
    'worm',
    'wrapper_(covering,_film,_seal,_wrap,_wrapper,_wrapping)',
    'wrench_(spanner,_wrench)',
    'yam',
    'yeast',
    'yoghurt',
    'zipper_(zip,_zipper)',
    'zucchini'
];

export const modality_values = [
    'audio',
    'imu',
    'gaze',
];

export const device_values = [
    'GoPro - Unknown Model',
    'GoPro Hero 4',
    'GoPro Hero Black 7',
    'GoPro Hero Black 8',
    'GoPro Hero Black 9',
    'GoPro Hero Silver 7',
    'GoPro Max',
    'LeaPower',
    'Ordro EP6 4K',
    'Pupil Labs Invisible',
    'Vuzix',
    'Weeview',
    'Zshade',
    'iVue Rincon 1080P',
    'unknown'
];

export const physical_setting_name_values = [
    'Baker',
    'Bike mechanic',
    'Carpenter',
    'Crafter',
    'Scooter mechanic',
    'barbershop',
    'boardgame',
    'card',
    'forest',
    'groupmeeting',
    'gym',
    'home',
    'hotpot',
    'milktea',
    'photo',
    'restaurant',
    'school',
    'tasession',
    'trail'
];

export const dimension_values = [
    '(1088, 1080)',
    '(1280, 720)',
    '(1440, 1080)',
    '(1440, 2880)',
    '(1920, 1080)',
    '(1920, 1440)',
    '(1921, 1080)',
    '(2560, 1440)',
    '(2560, 1920)',
    '(2880, 1080)',
    '(2880, 1440)',
    '(3413, 1920)',
    '(5760, 2880)',
    '(810, 1080)',
    '(None, None)'
];

export const video_source_values = [
    'bristol',
    'cmu',
    'cmu_africa',
    'frl_track_1_public',
    'georgiatech',
    'iiith',
    'indiana',
    'kaust',
    'minnesota',
    'nus',
    'uniandes',
    'unict',
    'utokyo'
];

export const split_values = [
    'av-train',
    'av-val',
    'fho_hands-train',
    'fho_hands-val',
    'fho_lta-train',
    'fho_lta-val',
    'fho_scod-train',
    'fho_scod-val',
    'fho_sta-train',
    'fho_sta-val',
    'moments-train',
    'moments-val',
    'nlq-train',
    'nlq-val',
    'vq-train',
    'vq-val'
];

export const benchmark_values = ['av', 'moments', 'vq', 'nlq', 'fho_hands', 'fho_lta', 'fho_scod', 'fho_sta'];

export const scenario_values = [
    'ATV scene',
    'Appointments: doctor, dentist',
    'Assembling a puzzle',
    'Assembling furniture',
    'Attending a TA session',
    'Attending a festival or fair',
    'Attending a lecture/class',
    'Attending a party',
    'Attending religious activity',
    'Attending sporting events - watching and participating in',
    "BBQ'ing/picnics",
    'Baker',
    'Baseball',
    'BasketBall',
    'Bike',
    'Bike mechanic',
    'Blacksmith',
    'Bowling',
    'Bus',
    'Camp setup/pack-up/chores',
    'Car - commuting, road trip',
    'Car mechanic',
    'Car/scooter washing',
    'Carpenter',
    'Cleaning / laundry',
    'Cleaning at the gym',
    'Climbing',
    'Clothes, other shopping',
    'Community cleaning',
    'Cooking',
    'Crafting/knitting/sewing/drawing/painting',
    'Crossword puzzle',
    'Cycling / jogging',
    'DEPRECATED : Playing board games',
    'Daily hygiene',
    'Dancing',
    'Doing hair/make-up',
    'Doing yardwork / shoveling snow',
    'Drive-thru food',
    'Drone flying',
    'Eating',
    "Eating at a friend's home",
    'Eating at a restaurant',
    'Eating at the cafeteria',
    'Eating in a canteen',
    'Eating in hawker center',
    'Electronics',
    'Farmer',
    'Fishing',
    'Fixing PC',
    'Fixing musical instrument',
    'Fixing something in the home',
    'Flower Picking',
    'Football',
    'Frisbee',
    'Gaming arcade / pool / billiards',
    'Gardener',
    'Gardening',
    'Getting car fixed',
    'Going to a salon (nail, hair, spa)',
    'Going to the gym - exercise machine, class, weights',
    'Going to the park',
    'Golfing',
    'Grinding mill',
    'Grocery shopping indoors',
    'Hair and Makeup stylist',
    'Handyman',
    'Hanging out at a coffee shop',
    'Hanging out with friends at a bar',
    'Hiking',
    'Hosting a party',
    'Household cleaners',
    'Household management - caring for kids',
    'Indoor Navigation (walking)',
    'Ironing',
    'Jobs Related to Construction',
    'Labwork',
    'Listening to music',
    'Maker Lab',
    'Making Bricks',
    'Making a salad/sandwich',
    'Making coffee',
    'Mehandi',
    'Mini golf',
    'On a screen (phone/laptop)',
    'Outdoor cooking',
    'Outdoor social (includes campfire)',
    'Outdoor technical climbing/belaying/rappelling (includes ropework)',
    'Participating in a meeting',
    'Play with cellphone',
    'Playing Darts',
    'Playing badminton',
    'Playing board games',
    'Playing cards',
    'Playing games / video games',
    'Playing with pets',
    'Potting plants (indoor)',
    'Practicing a musical instrument',
    'Preparing hopot',
    'Pulp Traces Factory (Egges)',
    'Reading books',
    'Reviewing flash cards',
    'Riding motorcycle',
    'Roller skating',
    'Rowing',
    'Scooter mechanic',
    'Skateboard/scooter',
    'Sleeping',
    'Snow sledding',
    'Street art',
    'Swimming in a pool/ocean',
    'Table tennis',
    'Taking photos in photography studio',
    'Talking on the phone',
    'Talking to colleagues',
    'Talking with family members',
    'Talking with friends/housemates',
    'Tourism',
    'Train',
    'Video call',
    'Visiting exhibition',
    'Walking on street',
    'Walking the dog / pet',
    'Washing the dog / pet, grooming horse',
    'Watching movies at the cinema',
    'Watching tv',
    'Working at desk',
    'Working in milktea shop',
    'Working in outdoor store',
    'Working out at home',
    'Working out outside',
    'Writing on whiteboard',
    'Yoga practice',
    'biology experiments',
    'building lego models / plastic models',
    'writing on book'
];
